import type { Metadata } from "next";
import { Inter, Lato, Lobster } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const lato = Lato({
	weight: "400",
	subsets: ["latin"],
	variable: "--font--lato",
});
const lobster = Lobster({
	weight: "400",
	subsets: ["latin"],
	variable: "--font--lobster",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${lobster.variable} ${lato.variable}`}>{children}</body>
    </html>
  );
}
